// mfe2/src/app/pages/page2/page2.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-page2',
  templateUrl: './page2.component.html',
  styleUrls: ['./page2.component.scss']
})
export class Page2Component {
  constructor(private route: ActivatedRoute, private router: Router) {}

  getBaseRoute() {
    const routePath = this.route.pathFromRoot.map(root => root.routeConfig)
      .filter(Boolean)
      .filter(route => !route?.component)

    return routePath.map(route => route?.path ?? '').filter(Boolean)
  }

  navigate() {
    const baseRoute = this.getBaseRoute()
    baseRoute.push('page1')

    this.router.navigate(baseRoute)
  }
}

<div class="page-container mfe-2-bg">
   <p class="text">Página 2 do mfe 2</p>

   <div class="flex">
     <button (click)="navigate()" class="button">
       Ir para página 1
     </button>
   </div>
 </div>

// mfe1/src/pages/Page2.tsx
import { useNavigate } from "react-router-dom";
import "../index.css";
import { getPath } from "../utils/getPath";

type PageProps = {
  baseUrl?: string;
};

export default function Page2({ baseUrl = "" }: PageProps) {
  const navigate = useNavigate();

  function onBtnClick() {
    const path = getPath(baseUrl, "page1");
    navigate(path);
  }

  return (
    <div className="page-container">
      <p className="text">Página 2 do mfe 1</p>

      <div className="flex">
        <button onClick={onBtnClick} className="button">
          Ir para página 1
        </button>
      </div>
    </div>
  );
}
