// mfe2/src/app/pages/page1/page1.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-page1',
  templateUrl: './page1.component.html',
  styleUrls: ['./page1.component.scss']
})
export class Page1Component {
  constructor(private route: ActivatedRoute, private router: Router) { }

  getBaseRoute() {
    const routePath = this.route.pathFromRoot.map(root => root.routeConfig)
      .filter(Boolean)
      .filter(route => !route?.component)

    return routePath.map(route => route?.path ?? '').filter(Boolean)
  }

  navigate() {
    const baseRoute = this.getBaseRoute()
    baseRoute.push('page2')

    this.router.navigate(baseRoute)
  }

  goBack() {
    window.history.back()
  }
}

<div class="page-container mfe-2-bg">
   <p class="text">Página 1 do mfe 2</p>

   <div class="flex">
     <button (click)="navigate()" class="button">
       Ir para página 2
     </button>

     <button class="button" (click)="goBack()">
       voltar
     </button>
   </div>
 </div>

// mfe1/src/pages/Page1.tsx
import { useNavigate } from "react-router-dom";
import "../index.css";
import { getPath } from "../utils/getPath";
import { PageProps } from "./types";

export default function Page1({ baseUrl = "" }: PageProps) {
  const navigate = useNavigate();

  function onBtnClick() {
    const path = getPath(baseUrl, "page2");
    navigate(path);
  }

  function goBack() {
    window.history.back();
  }

  return (
    <div className="page-container">
      <p className="text">Página 1 do mfe 1</p>

      <div className="flex">
        <button onClick={onBtnClick} className="button">
          Ir para página 2
        </button>

        <button className="button" onClick={goBack}>
          voltar
        </button>
      </div>
    </div>
  );
}
